#!/usr/bin/env python3
"""The in-app symbols the artwork pack does not contain, drawn to match it.

The pack has no transfers or log icon -- it is a set of things, not of
controls, and those two are the family's own ideas. They are drawn here in the
same language as `build_from_svg.py` emits: a 512 viewport with roughly 56px of
margin, solid fills from the family's palette, rounded ends, no strokes, no
gradients.

This is the symbol half of the authoring. The launcher and its per-app marks
live in `appicons/launcher.py`; the two share no state, so an app can build
whichever it needs.

Kept as code rather than as hand-written XML so the geometry is stated once
and the whole set can be re-rendered when the palette moves.

Usage:
    python3 icons/authored_symbols.py                        # preview into icons/build/
    python3 icons/authored_symbols.py --out PATH/res/drawable   # straight into an app
"""
from __future__ import annotations

import argparse
import math
import pathlib

HERE = pathlib.Path(__file__).resolve().parent

# Claude's clay and the warm neutrals that go with it; see tokens/color.md.
CLAY = "#C5613F"
CLAY_SOFT = "#E0A088"
CLAY_PALE = "#F6E0D6"
SLATE = "#574D45"
MIST = "#ECE5DC"
WHITE = "#FFFFFF"
# White at the alpha the pack's tiles put a background shape at.
GHOST_WHITE = "#8CFFFFFF"


def rounded_rect(x: float, y: float, w: float, h: float, r: float) -> str:
    """A rounded rectangle, as vector path data."""
    return (
        f"M{x + r},{y} L{x + w - r},{y} Q{x + w},{y} {x + w},{y + r} "
        f"L{x + w},{y + h - r} Q{x + w},{y + h} {x + w - r},{y + h} "
        f"L{x + r},{y + h} Q{x},{y + h} {x},{y + h - r} "
        f"L{x},{y + r} Q{x},{y} {x + r},{y} Z"
    )


def vector(paths: list[tuple[str, str]], size: int = 24) -> str:
    lines = [
        '<?xml version="1.0" encoding="utf-8"?>',
        "<!-- Generated by icons/authored_symbols.py. Do not edit by hand. -->",
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"',
        '    xmlns:aapt="http://schemas.android.com/aapt"',
        f'    android:width="{size}dp"',
        f'    android:height="{size}dp"',
        '    android:viewportWidth="512"',
        '    android:viewportHeight="512">',
    ]
    for fill, data in paths:
        if ":" in fill:
            # A gradient, written the long way round: a vector drawable can
            # only take one as a nested attribute, not as a colour string.
            start, end = fill.split(":")
            lines += [
                "    <path",
                f'        android:pathData="{data}">',
                '        <aapt:attr name="android:fillColor">',
                '            <gradient',
                '                android:type="linear"',
                '                android:startX="0" android:startY="0"',
                '                android:endX="512" android:endY="512"',
                f'                android:startColor="{start}"',
                f'                android:endColor="{end}" />',
                "        </aapt:attr>",
                "    </path>",
            ]
        else:
            lines += ["    <path", f'        android:fillColor="{fill}"',
                      f'        android:pathData="{data}" />']
    lines += ["</vector>", ""]
    return "\n".join(lines)


# The transfers mark: two lanes on a diagonal, one leaving and one arriving.
LANE_TRAVEL = -35.0     # up and to the right
LANE_OFFSET = 52.0      # how far each lane sits off the axis


def lane(offset: float, heading: float, scale: float = 1.0) -> str:
    """One tapered arrow, offset across the line of travel.

    Thin at the tail and full at the head, ending in a solid point. The tail
    is not brought to nothing: at 48px a tail that tapers to a hair vanishes
    and the arrow turns into a floating chevron.
    """
    across = math.radians(LANE_TRAVEL + 90.0)
    cx = 256.0 + offset * scale * math.cos(across)
    cy = 256.0 + offset * scale * math.sin(across)
    a = math.radians(heading)
    ux, uy = math.cos(a), math.sin(a)
    nx, ny = -uy, ux

    length, tail, head, tip_len, tip_half = (
        v * scale for v in (240.0, 22.0, 46.0, 62.0, 48.0)
    )

    def at(along: float, out: float) -> str:
        return f"{cx + ux * along + nx * out:.1f},{cy + uy * along + ny * out:.1f}"

    back = -length / 2
    neck = length / 2 - tip_len
    points = [
        at(back, tail / 2), at(neck, head / 2), at(neck, tip_half),
        at(length / 2, 0),
        at(neck, -tip_half), at(neck, -head / 2), at(back, -tail / 2),
    ]
    return "M" + " L".join(points) + " Z"


ICONS = {
    # Transfers: two lanes on a diagonal, one leaving and one arriving.
    # Drawn here rather than taken from the pack, which has no icon for a
    # queue. The leaving lane carries the accent.
    # 1.5 puts the tips 196 from the middle, which is the ~56px margin the
    # rest of the set is drawn to.
    "ic_flat_transfers": [
        (CLAY, lane(-LANE_OFFSET, LANE_TRAVEL, scale=1.5)),
        (CLAY_SOFT, lane(LANE_OFFSET, LANE_TRAVEL + 180.0, scale=1.5)),
    ],

    # Log: lines on a panel, the newest picked out. The last line is short,
    # which is what makes it read as a list rather than as a document.
    "ic_flat_log": [
        (MIST, rounded_rect(86, 96, 340, 320, 40)),
        (CLAY, rounded_rect(136, 152, 240, 36, 18)),
        (SLATE, rounded_rect(136, 238, 240, 36, 18)),
        (SLATE, rounded_rect(136, 324, 160, 36, 18)),
    ],
}

# The white-on-tile half of the set.
#
# Every place in the drawer wears a filled tile with a white glyph, and the
# transfer queue had no glyph of its own -- it wore a folder, which is what
# the row above it means. So the same two arrows are drawn again in white,
# the up one at the reduced alpha the pack's tiles use for the part of a
# shape that sits behind, so the pair reads as down-and-up rather than as a
# solid block.
TILES = {
    # The mark on the error card. Drawn here rather than taken from the pack,
    # whose warning icon is a white exclamation on an amber disc: two light
    # fills, which the tile builder's figure-from-ground rule reads as two
    # grounds and ghosts them both. A tile supplies its own disc anyway --
    # what it wants inside is the mark alone.
    "ic_tile_alert": [
        (WHITE, rounded_rect(225, 104, 62, 200, 31)),
        (WHITE, rounded_rect(218, 336, 76, 76, 38)),
    ],

    # Both lanes solid, unlike the file tiles. The reduced alpha there marks
    # the part of a shape that sits behind -- a document's page under its
    # lines. Here the two lanes are the two directions, and dimming one made
    # the mark read as one arrow with a shadow.
    "ic_tile_transfers": [
        (WHITE, lane(-LANE_OFFSET, LANE_TRAVEL, scale=1.5)),
        (WHITE, lane(LANE_OFFSET, LANE_TRAVEL + 180.0, scale=1.5)),
    ],
}


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out",
        type=pathlib.Path,
        default=HERE / "build",
        help="drawable directory to write into "
        "(an app points this at its own app/src/main/res/drawable; "
        "default: icons/build/ for preview)",
    )
    args = parser.parse_args()
    out: pathlib.Path = args.out
    out.mkdir(parents=True, exist_ok=True)

    for name, paths in ICONS.items():
        (out / f"{name}.xml").write_text(vector(paths))
        print(f"{name}.xml")
    for name, paths in TILES.items():
        (out / f"{name}.xml").write_text(vector(paths))
        print(f"{name}.xml")


if __name__ == "__main__":
    main()
